/**
 * RecruitOS Dynamic Email Template Engine (PHASE EM-01)
 * Generates dynamic, production-grade HTML and Plain Text emails for all platform events.
 * Fully multi-tenant aware with dynamic Agency branding and master layout system.
 */

export interface RenderedEmail {
  subject: string;
  html: string;
  text: string;
}

export interface BaseAgencyContext {
  agencyName?: string | null;
  logoUrl?: string | null;
  senderName?: string | null;
  replyToEmail?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  websiteUrl?: string | null;
}

const DEFAULT_BASE_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

/**
 * Master Email Layout Wrapper
 * Enforces responsive 700px max-width container, header branding, and RecruitOS footer.
 */
function wrapMasterLayout(
  agency: BaseAgencyContext,
  title: string,
  contentHtml: string,
  cta?: { label: string; url: string } | null
): string {
  const displayAgencyName = agency.agencyName || agency.senderName || 'RecruitOS Agency';
  const logoHtml = agency.logoUrl
    ? `<img src="${agency.logoUrl}" alt="${displayAgencyName}" style="max-height: 44px; width: auto; display: block; margin-bottom: 8px;" />`
    : '';

  const ctaButtonHtml = cta
    ? `
      <div style="margin: 32px 0 24px 0; text-align: center;">
        <a href="${cta.url}" target="_blank" style="background-color: #0d3859; color: #ffffff; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 800; padding: 14px 28px; text-decoration: none; border-radius: 8px; display: inline-block; box-shadow: 0 4px 6px -1px rgba(13, 56, 89, 0.2);">
          ${cta.label}
        </a>
      </div>
    `
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; }
    table { border-collapse: collapse; }
    @media only screen and (max-width: 640px) {
      .container { width: 100% !important; padding: 12px !important; }
      .content-box { padding: 20px 16px !important; }
      .table-responsive { display: block !important; width: 100% !important; overflow-x: auto !important; }
    }
  </style>
</head>
<body style="margin: 0; padding: 24px 0; background-color: #f8fafc;">
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td align="center">
        <!-- 700px Container -->
        <table role="presentation" class="container" width="700" border="0" cellspacing="0" cellpadding="0" style="width: 700px; max-width: 700px; margin: 0 auto;">
          
          <!-- Header Branding -->
          <tr>
            <td style="padding: 16px 24px; background-color: #ffffff; border-top-left-radius: 12px; border-top-right-radius: 12px; border-bottom: 2px solid #e2e8f0;">
              <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    ${logoHtml}
                    <div style="font-size: 20px; font-weight: 800; color: #0d3859; letter-spacing: -0.5px; text-transform: uppercase;">
                      ${displayAgencyName}
                    </div>
                  </td>
                  <td align="right" style="font-size: 11px; color: #64748b; font-weight: 600;">
                    Official Notification
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Main Body -->
          <tr>
            <td class="content-box" style="padding: 32px; background-color: #ffffff; border-bottom-left-radius: 12px; border-bottom-right-radius: 12px; box-shadow: 0 4px 12px rgba(15, 23, 42, 0.05);">
              
              <h2 style="margin: 0 0 20px 0; font-size: 20px; font-weight: 800; color: #0f172a; letter-spacing: -0.3px;">
                ${title}
              </h2>

              <div style="font-size: 14px; line-height: 1.6; color: #334155;">
                ${contentHtml}
              </div>

              ${ctaButtonHtml}

            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 24px 16px; text-align: center; font-size: 12px; color: #94a3b8; line-height: 1.5;">
              <p style="margin: 0 0 4px 0; font-weight: 600; color: #64748b;">
                ${displayAgencyName} ${agency.contactEmail ? `• ${agency.contactEmail}` : ''}
              </p>
              <p style="margin: 0;">
                This email was generated by <strong style="color: #0d3859;">RecruitOS</strong> Talent Platform
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

// =========================================================
// 1. REQUIREMENT RECEIVED TEMPLATE (Recipient: Agency Owner)
// =========================================================
export interface RequirementReceivedParams {
  agency: BaseAgencyContext;
  requirementId: string;
  positionTitle: string;
  companyName: string;
  contactPerson?: string;
  source?: string;
  receivedDate?: string;
  baseUrl?: string;
}

export function generateRequirementReceivedTemplate(params: RequirementReceivedParams): RenderedEmail {
  const { agency, requirementId, positionTitle, companyName, contactPerson, source, receivedDate, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `New Requirement Received - ${positionTitle}`;
  const ctaUrl = `${appUrl}/incoming-requirements/${requirementId}`;

  const htmlContent = `
    <p style="margin-top: 0;">A new client hiring requirement has been received and logged in your inbox pipeline.</p>

    <div style="background-color: #f1f5f9; border-left: 4px solid #0d3859; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #475569;">Requirement ID:</td><td>REQ-${requirementId.slice(0, 8).toUpperCase()}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Position Title:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Company Name:</td><td>${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Contact Person:</td><td>${contactPerson || 'N/A'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Source:</td><td>${source || 'Website Widget'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Received Date:</td><td>${receivedDate || new Date().toLocaleDateString('en-US')}</td></tr>
      </table>
    </div>

    <p>Please review the requirement details and assign a lead recruiter to start sourcing.</p>
  `;

  const textContent = `New Requirement Received - ${positionTitle}\n
Requirement ID: REQ-${requirementId.slice(0, 8).toUpperCase()}
Position: ${positionTitle}
Company: ${companyName}
Contact Person: ${contactPerson || 'N/A'}
Source: ${source || 'Website Widget'}
Received Date: ${receivedDate || new Date().toLocaleDateString('en-US')}

View Requirement: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'View Requirement', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 2. REQUIREMENT ASSIGNED TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface RequirementAssignedParams {
  agency: BaseAgencyContext;
  requirementId: string;
  positionTitle: string;
  companyName: string;
  priority?: string;
  assignedBy?: string;
  assignedDate?: string;
  baseUrl?: string;
}

export function generateRequirementAssignedTemplate(params: RequirementAssignedParams): RenderedEmail {
  const { agency, requirementId, positionTitle, companyName, priority, assignedBy, assignedDate, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `New Requirement Assigned - ${positionTitle}`;
  const ctaUrl = `${appUrl}/incoming-requirements/${requirementId}`;

  const htmlContent = `
    <p style="margin-top: 0;">You have been assigned as lead recruiter for a new hiring requirement.</p>

    <div style="background-color: #f1f5f9; border-left: 4px solid #0d3859; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #475569;">Position Title:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Company Name:</td><td>${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Priority:</td><td><span style="background-color: #e0f2fe; color: #0369a1; padding: 2px 8px; border-radius: 4px; font-weight: 700; font-size: 11px;">${(priority || 'HIGH').toUpperCase()}</span></td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Assigned By:</td><td>${assignedBy || 'Agency Administrator'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Assigned Date:</td><td>${assignedDate || new Date().toLocaleDateString('en-US')}</td></tr>
      </table>
    </div>

    <p>Click below to open the requirement workspace, review candidate specifications, and convert it to an active Job Mandate.</p>
  `;

  const textContent = `New Requirement Assigned - ${positionTitle}\n
Position: ${positionTitle}
Company: ${companyName}
Priority: ${priority || 'HIGH'}
Assigned By: ${assignedBy || 'Agency Administrator'}
Assigned Date: ${assignedDate || new Date().toLocaleDateString('en-US')}

Open Requirement: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Open Requirement', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 3. REQUIREMENT ACCEPTED TEMPLATE (Recipient: Client)
// =========================================================
export interface RequirementAcceptedParams {
  agency: BaseAgencyContext;
  clientName: string;
  positionTitle: string;
  companyName: string;
  recruiterName?: string;
  recruiterEmail?: string;
  recruiterPhone?: string;
  mandateId?: string;
  baseUrl?: string;
}

export function generateRequirementAcceptedTemplate(params: RequirementAcceptedParams): RenderedEmail {
  const { agency, clientName, positionTitle, companyName, recruiterName, recruiterEmail, recruiterPhone, mandateId, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Requirement Accepted - ${positionTitle}`;
  const ctaUrl = `${appUrl}/incoming-requirements/${mandateId || ''}`;

  const htmlContent = `
    <p style="margin-top: 0;">Dear <strong>${clientName}</strong>,</p>
    <p>Thank you for sharing your hiring requirement with us. Our recruitment team has reviewed and accepted the requirement.</p>

    <div style="background-color: #f1f5f9; border-left: 4px solid #10b981; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #475569;">Position Title:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Company Name:</td><td>${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Assigned Recruiter:</td><td style="font-weight: 700;">${recruiterName || 'Talent Sourcing Specialist'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Recruiter Email:</td><td>${recruiterEmail || agency.replyToEmail || 'contact@agency.com'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Recruiter Phone:</td><td>${recruiterPhone || agency.contactPhone || 'N/A'}</td></tr>
      </table>
    </div>

    <p>Our team has initiated candidate matching and headhunting for this mandate. We will share shortlisted candidate profiles shortly.</p>
  `;

  const textContent = `Dear ${clientName},\n
Thank you for sharing your hiring requirement. Our recruitment team has reviewed and accepted the requirement.\n
Position: ${positionTitle}
Company: ${companyName}
Assigned Recruiter: ${recruiterName || 'Talent Sourcing Specialist'}
Recruiter Email: ${recruiterEmail || agency.replyToEmail || 'contact@agency.com'}
Recruiter Phone: ${recruiterPhone || 'N/A'}

View Requirement Status: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'View Requirement Status', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 4. REQUIREMENT REJECTED TEMPLATE (Recipient: Client)
// =========================================================
export interface RequirementRejectedParams {
  agency: BaseAgencyContext;
  clientName: string;
  positionTitle: string;
  companyName: string;
  reason?: string;
}

export function generateRequirementRejectedTemplate(params: RequirementRejectedParams): RenderedEmail {
  const { agency, clientName, positionTitle, companyName, reason } = params;
  const title = `Requirement Update - ${positionTitle}`;

  const htmlContent = `
    <p style="margin-top: 0;">Dear <strong>${clientName}</strong>,</p>
    <p>Thank you for submitting your hiring requirement for <strong>${positionTitle}</strong> (${companyName}).</p>
    <p>After reviewing our current capacity and domain focus, we regret to inform you that we are unable to accept this specific requirement at this time.</p>

    ${
      reason
        ? `<div style="background-color: #fff1f2; border-left: 4px solid #e11d48; padding: 16px; border-radius: 6px; margin: 20px 0; font-size: 13px; color: #9f1239;">
            <strong>Reason for Non-Acceptance:</strong><br />${reason}
          </div>`
        : ''
    }

    <p>We appreciate your interest in partnering with us and look forward to collaborating on future hiring needs.</p>
  `;

  const textContent = `Dear ${clientName},\n
Thank you for submitting your hiring requirement for ${positionTitle} (${companyName}).
Regrettably, we are unable to accept this requirement at this time.

${reason ? `Reason: ${reason}\n` : ''}
We appreciate your interest in working with us.`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, null),
    text: textContent
  };
}

// =========================================================
// 5. CANDIDATE SUBMISSION TRACKER TEMPLATE (Recipient: Client)
// =========================================================
export interface CandidateTrackerRow {
  date?: string;
  source?: string;
  clientName?: string;
  appliedPositionName?: string;
  candidateName: string;
  emailId: string;
  number: string;
  location: string;
  readyToRelocate: string;
  experience: string;
  relevantExperience: string;
  designation: string;
  qualification: string;
  currentLastCompany: string;
  currentSalary: string;
  expectedSalary: string;
  noticePeriod: string;
  reasonOfLeaving: string;
  offerInHand: string;
  resumeUrl?: string | null;
}

export interface CandidateSubmissionTemplateParams {
  agency: BaseAgencyContext;
  clientName: string;
  positionTitle: string;
  recruiterCoverNote?: string;
  token: string;
  candidates: CandidateTrackerRow[];
  baseUrl?: string;
}

export function generateCandidateSubmissionTemplate(params: CandidateSubmissionTemplateParams): RenderedEmail {
  const { agency, clientName, positionTitle, recruiterCoverNote, token, candidates, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Candidate Submission Tracker - ${positionTitle}`;
  const reviewPortalUrl = `${appUrl}/client-review/${token}`;

  const rowsHtml = candidates.map(c => `
    <tr style="border-bottom: 1px solid #cbd5e1;">
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px; font-weight: 500;">${c.date || new Date().toLocaleDateString()}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.source || 'Headhunted'}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.clientName || clientName}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px; font-weight: 600;">${c.appliedPositionName || positionTitle}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px; font-weight: 700; color: #0d3859;">${c.candidateName}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.emailId}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.number}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.location}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.readyToRelocate}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.experience}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.relevantExperience}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.designation}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.qualification}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.currentLastCompany}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.currentSalary}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.expectedSalary}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.noticePeriod}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.reasonOfLeaving}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.offerInHand}</td>
      <td style="padding: 8px; text-align: center; font-size: 11px;">
        ${c.resumeUrl 
          ? `<a href="${c.resumeUrl}" target="_blank" style="color: #0284c7; font-weight: 700; text-decoration: underline;">View Resume</a>`
          : '<span style="color: #94a3b8;">N/A</span>'}
      </td>
    </tr>
  `).join('');

  const htmlContent = `
    <p style="margin-top: 0;">Dear <strong>${clientName}</strong>,</p>
    <p>Please find below the candidate shortlist for <strong>${positionTitle}</strong> submitted for your review.</p>

    ${
      recruiterCoverNote
        ? `<div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #0d3859; padding: 14px; border-radius: 6px; margin: 16px 0; font-size: 13px; color: #334155;">
            <strong style="color: #0d3859;">Recruiter Note:</strong><br />${recruiterCoverNote}
          </div>`
        : ''
    }

    <div style="margin: 24px 0; text-align: center;">
      <a href="${reviewPortalUrl}" target="_blank" style="background-color: #0d3859; color: #ffffff; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 800; padding: 14px 28px; text-decoration: none; border-radius: 8px; display: inline-block;">
        Review Submitted Candidates
      </a>
    </div>

    <!-- 19-Column Candidate Tracker Table -->
    <div style="margin-top: 24px; overflow-x: auto; -webkit-overflow-scrolling: touch;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="min-width: 1200px; border: 1px solid #cbd5e1; border-collapse: collapse; font-size: 11px; text-align: left;">
        <thead>
          <tr style="background-color: #0d3859; color: #ffffff; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px;">
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Date</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Source</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Client Name</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Applied Position Name</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Candidate Name</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Email ID</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Number</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Location</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Ready To Relocate</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Experience</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Relevant Experience</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Designation</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Qualification</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Current/Last Company</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Current Salary</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Expected Salary</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Notice Period</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Reason Of Leaving</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Offer In Hand</th>
            <th style="padding: 10px 8px; text-align: center;">Resume</th>
          </tr>
        </thead>
        <tbody style="background-color: #ffffff; color: #1e293b;">
          ${rowsHtml}
        </tbody>
      </table>
    </div>

    <p style="margin-top: 24px;">Please click the button above to record your interview decisions (Shortlist / Hold / Reject) for each candidate.</p>
  `;

  const textContent = `Dear ${clientName},\n
Candidate Submission Tracker - ${positionTitle}\n
Total Candidates: ${candidates.length}
${recruiterCoverNote ? `Recruiter Note: ${recruiterCoverNote}\n` : ''}
Access Review Portal: ${reviewPortalUrl}\n
Candidates:\n${candidates.map(c => `- ${c.candidateName} | ${c.designation} | Exp: ${c.experience} | Current CTC: ${c.currentSalary} | Notice: ${c.noticePeriod}`).join('\n')}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Review Submitted Candidates', url: reviewPortalUrl }),
    text: textContent
  };
}

// =========================================================
// 6. CLIENT INTERVIEW TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface ClientInterviewParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  clientName: string;
  submissionId?: string;
  baseUrl?: string;
}

export function generateInterviewSelectedTemplate(params: ClientInterviewParams): RenderedEmail {
  const { agency, candidateName, positionTitle, clientName, submissionId, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Client Selected Candidate For Interview`;
  const ctaUrl = `${appUrl}/submissions`;

  const htmlContent = `
    <p style="margin-top: 0;">Great news! The client has selected a candidate for an interview.</p>

    <div style="background-color: #ecfdf5; border-left: 4px solid #10b981; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #047857;">Candidate Name:</td><td style="font-weight: 800; color: #065f46;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Position:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Client Name:</td><td>${clientName}</td></tr>
      </table>
    </div>

    <p>Please log into RecruitOS to schedule interview slots with the candidate and client team.</p>
  `;

  const textContent = `Client Selected Candidate For Interview\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Client Name: ${clientName}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: textContent
  };
}

// =========================================================
// 7. CLIENT HOLD TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface ClientHoldParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  clientName: string;
  notes?: string;
  baseUrl?: string;
}

export function generateCandidateHoldTemplate(params: ClientHoldParams): RenderedEmail {
  const { agency, candidateName, positionTitle, clientName, notes, baseUrl } = params;
  const title = `Candidate Put On Hold By Client - ${candidateName}`;

  const htmlContent = `
    <p style="margin-top: 0;">The client has put a submitted candidate on hold.</p>

    <div style="background-color: #fffbeb; border-left: 4px solid #f59e0b; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #b45309;">Candidate Name:</td><td style="font-weight: 800; color: #78350f;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #b45309;">Position:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #b45309;">Client Name:</td><td>${clientName}</td></tr>
        ${notes ? `<tr><td style="font-weight: 700; color: #b45309;">Client Notes / Reason:</td><td style="font-weight: 700; color: #d97706;">${notes}</td></tr>` : ''}
      </table>
    </div>

    <p>The candidate status has been updated to ON_HOLD in the recruitment pipeline.</p>
  `;

  const textContent = `Candidate Put On Hold By Client - ${candidateName}\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Client Name: ${clientName}
${notes ? `Client Notes: ${notes}\n` : ''}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: textContent
  };
}

// =========================================================
// 8. CLIENT REJECT TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface ClientRejectParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  clientName: string;
  notes?: string;
  baseUrl?: string;
}

export function generateCandidateRejectedTemplate(params: ClientRejectParams): RenderedEmail {
  const { agency, candidateName, positionTitle, clientName, notes, baseUrl } = params;
  const title = `Candidate Rejected By Client - ${candidateName}`;

  const htmlContent = `
    <p style="margin-top: 0;">The client has declined a submitted candidate profile.</p>

    <div style="background-color: #fff1f2; border-left: 4px solid #e11d48; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #be123c;">Candidate Name:</td><td style="font-weight: 800; color: #881337;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #be123c;">Position:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #be123c;">Client Name:</td><td>${clientName}</td></tr>
        ${notes ? `<tr><td style="font-weight: 700; color: #be123c;">Rejection Reason / Notes:</td><td style="font-weight: 700; color: #be123c;">${notes}</td></tr>` : ''}
      </table>
    </div>

    <p>Please review candidate pipeline feedback and continue sourcing alternative matches.</p>
  `;

  const textContent = `Candidate Rejected By Client - ${candidateName}\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Client Name: ${clientName}
${notes ? `Rejection Reason: ${notes}\n` : ''}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: textContent
  };
}

// =========================================================
// 9. SUBSCRIPTION EXPIRY TEMPLATE (Recipient: Agency Owners / Super Admin)
// =========================================================
export interface SubscriptionExpiryParams {
  agency: BaseAgencyContext;
  agencyName: string;
  planName?: string;
  expiryDate?: string;
  daysRemaining: number;
  baseUrl?: string;
}

export function generateSubscriptionExpiryTemplate(params: SubscriptionExpiryParams): RenderedEmail {
  const { agency, agencyName, planName, expiryDate, daysRemaining, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Subscription Expiring Soon - ${agencyName}`;
  const ctaUrl = `${appUrl}/settings`;

  const htmlContent = `
    <p style="margin-top: 0;">This is an automated alert that your agency subscription plan is approaching its expiration date.</p>

    <div style="background-color: #fffbeb; border-left: 4px solid #d97706; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #92400e;">Agency Name:</td><td style="font-weight: 800; color: #0d3859;">${agencyName}</td></tr>
        <tr><td style="font-weight: 700; color: #92400e;">Subscription Plan:</td><td>${planName || 'Enterprise Tier'}</td></tr>
        <tr><td style="font-weight: 700; color: #92400e;">Expiration Date:</td><td>${expiryDate || 'Within 7 Days'}</td></tr>
        <tr><td style="font-weight: 700; color: #92400e;">Days Remaining:</td><td><strong style="color: #dc2626; font-size: 15px;">${daysRemaining} Day(s)</strong></td></tr>
      </table>
    </div>

    <p>Please renew your subscription to maintain uninterrupted platform access, active client portals, and job board widgets.</p>
  `;

  const textContent = `Subscription Expiring Soon - ${agencyName}\n
Agency Name: ${agencyName}
Subscription Plan: ${planName || 'Enterprise Tier'}
Expiration Date: ${expiryDate || 'Within 7 Days'}
Days Remaining: ${daysRemaining} Day(s)

Manage Subscription: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Manage Subscription', url: ctaUrl }),
    text: textContent
  };
}
export interface ClientInterviewInvitationParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  companyName: string;
  interviewType: string;
  interviewNotes?: string | null;
  slots?: Array<{ id?: string; index: number; dateTimeStr: string; dayDateStr?: string; timeTzStr?: string }>;
  calendlyUrl?: string | null;
  token: string;
  baseUrl?: string;
}

export function generateClientInterviewInvitationTemplate(params: ClientInterviewInvitationParams): RenderedEmail {
  const { agency, candidateName, positionTitle, companyName, interviewType, interviewNotes, slots, calendlyUrl, token, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Interview Invitation: ${positionTitle} at ${companyName}`;

  const DEFAULT_CALENDLY_URL = 'https://calendly.com/divyanshu-botspring/30min';
  const activeCalendlyUrl = calendlyUrl?.trim() || DEFAULT_CALENDLY_URL;

  let schedulingSectionHtml = '';
  let schedulingSectionText = '';

  if (activeCalendlyUrl) {
    schedulingSectionHtml = `
      <div style="background-color: #f0f7ff; border: 2px solid #0069ff; border-radius: 12px; padding: 24px; text-align: center; margin: 24px 0;">
        <p style="margin: 0 0 8px 0; font-size: 16px; font-weight: 800; color: #0d3859;">
          🗓️ Select Your Preferred Interview Time
        </p>
        <p style="margin: 0 0 16px 0; font-size: 13px; color: #475569; line-height: 1.5;">
          Please click the button below to view available dates and book your interview slot via Calendly.
        </p>
        <div style="margin: 16px 0;">
          <a href="${activeCalendlyUrl}" target="_blank" style="display: inline-block; background-color: #0069ff; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 800; font-size: 15px; text-align: center; box-shadow: 0 4px 12px rgba(0, 105, 255, 0.3);">
            📅 Open Calendly & Book Interview Slot
          </a>
        </div>
        <p style="margin: 12px 0 0 0; font-size: 11px; color: #64748b;">
          Direct calendar booking via Calendly.
        </p>
      </div>
    `;
    schedulingSectionText = `Schedule Your Interview on Calendly:\n${activeCalendlyUrl}`;
  } else if (slots && slots.length > 0) {
    const slotButtonsHtml = slots.map((s) => {
      const slotIdParam = s.id ? `?slotId=${s.id}` : '';
      const confirmUrl = `${appUrl}/interview/confirm-slot/${token}${slotIdParam}`;
      const buttonLabel = s.dayDateStr && s.timeTzStr
        ? `[ ${s.dayDateStr} - ${s.timeTzStr} ]`
        : `[ ${s.dateTimeStr} ]`;

      return `
        <div style="margin: 12px 0;">
          <a href="${confirmUrl}" target="_blank" style="display: block; background-color: #0d3859; color: #ffffff; text-decoration: none; padding: 14px 20px; border-radius: 8px; font-weight: 700; font-size: 14px; text-align: center; box-shadow: 0 4px 6px -1px rgba(13, 56, 89, 0.2);">
            ${buttonLabel}
          </a>
        </div>
      `;
    }).join('');

    schedulingSectionHtml = `
      <p style="font-weight: 700; color: #0f172a; margin-top: 24px; margin-bottom: 12px;">Please choose one of the available interview slots:</p>
      <div style="margin-bottom: 24px;">
        ${slotButtonsHtml}
      </div>
    `;
    schedulingSectionText = `Please choose one of the available interview slots:\n${slots.map((s, i) => `${i + 1}. ${s.dateTimeStr} -> ${appUrl}/interview/confirm-slot/${token}${s.id ? `?slotId=${s.id}` : ''}`).join('\n')}`;
  }

  const htmlContent = `
    <p style="margin-top: 0;">Hello <strong>${candidateName}</strong>,</p>
    <p>You have been invited for an interview for the position of <strong>${positionTitle}</strong> at <strong>${companyName}</strong>.</p>

    <div style="background-color: #f1f5f9; border-left: 4px solid #0d3859; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #475569;">Candidate Name:</td><td style="font-weight: 800; color: #0d3859;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Position Title:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Company Name:</td><td style="font-weight: 700;">${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Interview Round:</td><td><span style="background-color: #e0f2fe; color: #0369a1; padding: 2px 8px; border-radius: 4px; font-weight: 700; font-size: 11px;">${interviewType}</span></td></tr>
        ${interviewNotes ? `<tr><td style="font-weight: 700; color: #475569;">Client Notes:</td><td>${interviewNotes}</td></tr>` : ''}
      </table>
    </div>

    ${schedulingSectionHtml}
  `;

  const textContent = `Interview Invitation: ${positionTitle} at ${companyName}\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Company: ${companyName}
Interview Round: ${interviewType}
${interviewNotes ? `Notes: ${interviewNotes}\n` : ''}
${schedulingSectionText}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, null),
    text: textContent
  };
}

// =========================================================
// 11. INTERVIEW SLOT SELECTED TEMPLATE (Section C)
// =========================================================
export interface InterviewSlotSelectedParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  companyName: string;
  interviewType: string;
  selectedSlotStr: string;
  meetingUrl?: string | null;
  timezoneStr?: string;
  recipientType?: 'CANDIDATE' | 'RECRUITER' | 'CLIENT';
  baseUrl?: string;
}

export function generateInterviewSlotSelectedTemplate(params: InterviewSlotSelectedParams): RenderedEmail {
  const { agency, candidateName, positionTitle, companyName, interviewType, selectedSlotStr, meetingUrl, timezoneStr, recipientType = 'CANDIDATE', baseUrl } = params;
  const tzName = timezoneStr || 'IST (UTC+5:30)';
  
  let subject = `Interview Confirmed - ${positionTitle}`;
  if (recipientType === 'RECRUITER') {
    subject = `Candidate Interview Confirmed - ${candidateName}`;
  } else if (recipientType === 'CLIENT') {
    subject = `Interview Slot Confirmed - ${candidateName}`;
  }

  const meetingLinkDisplay = meetingUrl || `https://meet.jit.si/recruitos-interview-${encodeURIComponent(candidateName.toLowerCase().replace(/\s+/g, '-'))}`;
  const cta = { label: 'Join Interview', url: meetingLinkDisplay };

  const htmlContent = `
    <p style="margin-top: 0;">The interview slot has been officially confirmed and scheduled.</p>

    <div style="background-color: #ecfdf5; border-left: 4px solid #10b981; padding: 18px; border-radius: 8px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="5" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #047857;">Candidate Name:</td><td style="font-weight: 800; color: #065f46;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Position Title:</td><td style="font-weight: 800; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Company:</td><td style="font-weight: 700;">${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Interview Round:</td><td>${interviewType}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Confirmed Date & Time:</td><td style="font-weight: 800; color: #0d3859;">${selectedSlotStr}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Timezone:</td><td style="font-weight: 600; color: #475569;">${tzName}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Meeting Link:</td><td><a href="${meetingLinkDisplay}" target="_blank" style="color: #0284c7; font-weight: 700; word-break: break-all;">${meetingLinkDisplay}</a></td></tr>
      </table>
    </div>

    <p style="font-size: 13px; color: #475569;">Please ensure you join 5 minutes prior to the scheduled start time.</p>
  `;

  const textContent = `${subject}\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Company: ${companyName}
Interview Round: ${interviewType}
Confirmed Time: ${selectedSlotStr}
Timezone: ${tzName}
Meeting Link: ${meetingLinkDisplay}

Join Interview: ${meetingLinkDisplay}`;

  return {
    subject,
    html: wrapMasterLayout(agency, subject, htmlContent, cta),
    text: textContent
  };
}

// =========================================================
// 12. INTERVIEW OUTCOME TEMPLATE (SELECTED / HOLD / REJECTED)
// =========================================================
export interface InterviewOutcomeParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  companyName: string;
  decision: 'SELECTED' | 'HOLD' | 'REJECTED';
  feedbackNotes?: string;
  recipientRole: 'CANDIDATE' | 'RECRUITER' | 'CLIENT';
  baseUrl?: string;
}

export function generateInterviewOutcomeTemplate(params: InterviewOutcomeParams): RenderedEmail {
  const { agency, candidateName, positionTitle, companyName, decision, feedbackNotes, recipientRole, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;

  let title = '';
  let statusBadgeColor = '#0284c7';
  let statusBadgeBg = '#e0f2fe';
  let headline = '';

  if (decision === 'SELECTED') {
    title = `Interview Outcome: Selected - ${candidateName} (${positionTitle})`;
    statusBadgeColor = '#065f46';
    statusBadgeBg = '#d1fae5';
    headline = recipientRole === 'CANDIDATE'
      ? `Congratulations! You have been <strong>SELECTED</strong> following your interview for ${positionTitle} at ${companyName}.`
      : `Candidate <strong>${candidateName}</strong> has been <strong>SELECTED</strong> for ${positionTitle} at ${companyName}.`;
  } else if (decision === 'HOLD') {
    title = `Interview Outcome: On Hold - ${candidateName} (${positionTitle})`;
    statusBadgeColor = '#b45309';
    statusBadgeBg = '#fef3c7';
    headline = recipientRole === 'CANDIDATE'
      ? `Your interview for ${positionTitle} at ${companyName} has been placed <strong>ON HOLD</strong>.`
      : `Candidate <strong>${candidateName}</strong> has been placed <strong>ON HOLD</strong> for ${positionTitle} at ${companyName}.`;
  } else {
    title = `Interview Outcome: Rejected - ${candidateName} (${positionTitle})`;
    statusBadgeColor = '#991b1b';
    statusBadgeBg = '#fee2e2';
    headline = recipientRole === 'CANDIDATE'
      ? `Thank you for taking the time to interview for ${positionTitle} at ${companyName}.`
      : `Candidate <strong>${candidateName}</strong> was <strong>REJECTED</strong> following the interview for ${positionTitle} at ${companyName}.`;
  }

  const htmlContent = `
    <p style="margin-top: 0;">${headline}</p>

    <div style="background-color: ${statusBadgeBg}; border-left: 4px solid ${statusBadgeColor}; padding: 18px; border-radius: 8px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="5" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700;">Candidate Name:</td><td style="font-weight: 800;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700;">Position Title:</td><td style="font-weight: 800;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700;">Company:</td><td style="font-weight: 700;">${companyName}</td></tr>
        <tr><td style="font-weight: 700;">Decision:</td><td><span style="background-color: ${statusBadgeBg}; color: ${statusBadgeColor}; padding: 2px 8px; border-radius: 4px; font-weight: 800; font-size: 11px;">${decision}</span></td></tr>
        ${feedbackNotes ? `<tr><td style="font-weight: 700; vertical-align: top;">Client Feedback:</td><td style="font-style: italic; color: #334155;">"${feedbackNotes}"</td></tr>` : ''}
      </table>
    </div>
  `;

  const textContent = `${title}\n
Candidate: ${candidateName}
Position: ${positionTitle}
Company: ${companyName}
Decision: ${decision}
${feedbackNotes ? `Feedback Notes: ${feedbackNotes}` : ''}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, recipientRole !== 'CANDIDATE' ? { label: 'Open RecruitOS Dashboard', url: `${appUrl}/submissions` } : undefined),
    text: textContent
  };
}

// =========================================================
// 13. INTERVIEW PREPARATION KIT TEMPLATE (INITIAL & REMINDERS)
// =========================================================
export interface InterviewPrepKitEmailParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  companyName: string;
  roundType: string;
  interviewDateStr: string;
  secureToken: string;
  isReminder?: boolean;
  isFinalReminder?: boolean;
  baseUrl?: string;
}

export function generateInterviewPrepKitTemplate(params: InterviewPrepKitEmailParams): RenderedEmail {
  const {
    agency,
    candidateName,
    positionTitle,
    companyName,
    roundType,
    interviewDateStr,
    secureToken,
    isReminder,
    isFinalReminder,
    baseUrl
  } = params;

  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const prepUrl = `${appUrl}/interview/preparation/${secureToken}`;

  let title = `Interview Preparation Kit - ${positionTitle}`;
  let bannerNote = `Your customized Interview Preparation Kit for <strong>${positionTitle}</strong> at <strong>${companyName}</strong> is ready.`;

  if (isFinalReminder) {
    title = `FINAL REMINDER: Review Interview Preparation Kit (1 Hour Left)`;
    bannerNote = `⚡ <strong>Urgent:</strong> Your interview starts in 1 hour. Please review your Preparation Kit to ensure readiness!`;
  } else if (isReminder) {
    title = `Reminder: Interview Preparation Kit - ${positionTitle}`;
    bannerNote = `⏰ <strong>Reminder:</strong> Your interview is scheduled in 7 hours. Don't forget to review your Preparation Kit!`;
  }

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Hi <strong>${candidateName}</strong>,</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.5;">${bannerNote}</p>

    <div style="background-color: #f8fafc; border: 1px solid #cbd5e1; border-left: 4px solid #0284c7; padding: 18px; border-radius: 8px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="5" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #0284c7;">Candidate Name:</td><td style="font-weight: 800;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #0284c7;">Position Title:</td><td style="font-weight: 800;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #0284c7;">Company Name:</td><td style="font-weight: 700;">${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #0284c7;">Interview Round:</td><td style="font-weight: 700; color: #b45309;">${roundType}</td></tr>
        <tr><td style="font-weight: 700; color: #0284c7;">Scheduled Time:</td><td style="font-weight: 800; color: #0f172a;">${interviewDateStr}</td></tr>
      </table>
    </div>

    <p style="font-size: 13px; color: #475569;">Inside your preparation portal, you will find company insights, technical topics to revise, meeting guidelines, and a readiness checklist.</p>
  `;

  const textContent = `${title}\n
Hi ${candidateName},

Position: ${positionTitle}
Company: ${companyName}
Round: ${roundType}
Scheduled Time: ${interviewDateStr}

Review Preparation Kit: ${prepUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Review Preparation Kit', url: prepUrl }),
    text: textContent
  };
}

// =========================================================
// OF-01 EMAIL TEMPLATES
// =========================================================

export interface OfferSentEmailParams {
  agency: BaseAgencyContext;
  candidateName: string;
  companyName: string;
  positionTitle: string;
  offeredCtcStr: string;
  offerUrl: string;
}

export function generateOfferSentTemplate(params: OfferSentEmailParams): RenderedEmail {
  const { agency, candidateName, companyName, positionTitle, offeredCtcStr, offerUrl } = params;
  const title = `Official Employment Offer: ${positionTitle} at ${companyName}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Dear <strong>${candidateName}</strong>,</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.5;">Congratulations! We are pleased to extend an official employment offer for the position of <strong>${positionTitle}</strong> with <strong>${companyName}</strong>.</p>

    <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; border-left: 4px solid #16a34a; padding: 18px; border-radius: 8px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="5" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #15803d;">Company:</td><td style="font-weight: 800;">${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #15803d;">Position:</td><td style="font-weight: 800;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #15803d;">Offered Annual Compensation:</td><td style="font-weight: 800; color: #047857; font-size: 15px;">${offeredCtcStr}</td></tr>
      </table>
    </div>

    <p style="font-size: 13px; color: #475569;">Please click the button below to view full offer details, compensation structure, terms, and submit your response.</p>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Review & Respond to Offer', url: offerUrl }),
    text: `Offer Extended: ${positionTitle} at ${companyName}\nReview Offer: ${offerUrl}`
  };
}

export function generateOfferAcceptedTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  companyName: string;
  positionTitle: string;
  joiningDateStr: string;
  offeredCtcStr: string;
}): RenderedEmail {
  const { agency, candidateName, companyName, positionTitle, joiningDateStr, offeredCtcStr } = params;
  const title = `Offer ACCEPTED by ${candidateName} - ${positionTitle}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Great news! Candidate <strong>${candidateName}</strong> has officially accepted the employment offer for <strong>${positionTitle}</strong> at <strong>${companyName}</strong>.</p>

    <div style="background-color: #ecfdf5; border-left: 4px solid #059669; padding: 16px; border-radius: 8px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #047857;">Candidate:</td><td style="font-weight: 800;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Company:</td><td style="font-weight: 800;">${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Position:</td><td style="font-weight: 700;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Joining Date:</td><td style="font-weight: 800; color: #065f46;">${joiningDateStr}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Offered CTC:</td><td style="font-weight: 800;">${offeredCtcStr}</td></tr>
      </table>
    </div>

    <p style="font-size: 13px; color: #475569;">The pre-joining document verification process has been initialized in Joining Tracker.</p>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Offer Accepted by ${candidateName} for ${positionTitle} at ${companyName}. Expected Joining: ${joiningDateStr}`
  };
}

export function generateOfferDeclinedTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  companyName: string;
  positionTitle: string;
  declineReason?: string;
}): RenderedEmail {
  const { agency, candidateName, companyName, positionTitle, declineReason } = params;
  const title = `Offer Declined by ${candidateName} - ${positionTitle}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Candidate <strong>${candidateName}</strong> has declined the employment offer for <strong>${positionTitle}</strong> at <strong>${companyName}</strong>.</p>

    <div style="background-color: #fff1f2; border-left: 4px solid #e11d48; padding: 16px; border-radius: 8px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #be123c;">Candidate:</td><td style="font-weight: 800;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #be123c;">Company:</td><td style="font-weight: 800;">${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #be123c;">Reason Provided:</td><td style="font-weight: 700; color: #9f1239;">${declineReason || 'No specific reason specified'}</td></tr>
      </table>
    </div>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Offer Declined by ${candidateName} for ${positionTitle}. Reason: ${declineReason || 'None specified'}`
  };
}

export function generateOfferClarificationTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  companyName: string;
  positionTitle: string;
  questionTitle: string;
  questionDetails: string;
}): RenderedEmail {
  const { agency, candidateName, companyName, positionTitle, questionTitle, questionDetails } = params;
  const title = `Offer Clarification Requested by ${candidateName}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Candidate <strong>${candidateName}</strong> has requested clarification regarding their offer for <strong>${positionTitle}</strong> at <strong>${companyName}</strong>.</p>

    <div style="background-color: #fffbeb; border-left: 4px solid #d97706; padding: 16px; border-radius: 8px; margin: 20px 0;">
      <p style="font-weight: 800; color: #92400e; margin-top: 0;">${questionTitle}</p>
      <p style="font-size: 13px; color: #1e293b; white-space: pre-wrap;">${questionDetails}</p>
    </div>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Offer Clarification Requested by ${candidateName}: ${questionTitle} - ${questionDetails}`
  };
}

export function generateJoiningReminderTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  companyName: string;
  positionTitle: string;
  joiningDateStr: string;
  daysLeft: number;
}): RenderedEmail {
  const { agency, candidateName, companyName, positionTitle, joiningDateStr, daysLeft } = params;
  const title = `Reminder: Joining Date in ${daysLeft} Day(s) - ${positionTitle} at ${companyName}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Hi <strong>${candidateName}</strong>,</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.5;">This is a friendly reminder that your joining date with <strong>${companyName}</strong> for the role of <strong>${positionTitle}</strong> is coming up in <strong>${daysLeft} day(s)</strong> on <strong>${joiningDateStr}</strong>.</p>

    <div style="background-color: #f0f9ff; border-left: 4px solid #0284c7; padding: 16px; border-radius: 8px; margin: 20px 0;">
      <p style="margin: 0; font-size: 13px; color: #0369a1; font-weight: 700;">Please ensure all requested pre-joining documentation has been uploaded.</p>
    </div>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Joining Reminder: Your joining with ${companyName} is in ${daysLeft} day(s) on ${joiningDateStr}`
  };
}

export function generateJoiningConfirmedTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  companyName: string;
  positionTitle: string;
  joiningDateStr: string;
  finalSalaryStr: string;
}): RenderedEmail {
  const { agency, candidateName, companyName, positionTitle, joiningDateStr, finalSalaryStr } = params;
  const title = `PLACEMENT CONFIRMED: ${candidateName} Joined ${companyName}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">🎉 Successful Placement Confirmed!</p>
    <p style="font-size: 13.5px; color: #334155;">Both recruiter and client have officially confirmed that <strong>${candidateName}</strong> has joined <strong>${companyName}</strong> as <strong>${positionTitle}</strong>.</p>

    <div style="background-color: #f0fdf4; border-left: 4px solid #16a34a; padding: 16px; border-radius: 8px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #15803d;">Candidate:</td><td style="font-weight: 800;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #15803d;">Company:</td><td style="font-weight: 800;">${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #15803d;">Position:</td><td style="font-weight: 700;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #15803d;">Joined On:</td><td style="font-weight: 800; color: #047857;">${joiningDateStr}</td></tr>
        <tr><td style="font-weight: 700; color: #15803d;">Final Salary:</td><td style="font-weight: 800;">${finalSalaryStr}</td></tr>
      </table>
    </div>

    <p style="font-size: 13px; color: #475569;">A placement record and revenue ledger entry have been generated.</p>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Placement Confirmed: ${candidateName} joined ${companyName} on ${joiningDateStr}`
  };
}

export function generatePlacementClosedTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  companyName: string;
  revenueStr: string;
}): RenderedEmail {
  const { agency, candidateName, companyName, revenueStr } = params;
  const title = `Revenue Invoiced: Placement Closed for ${candidateName} at ${companyName}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Placement closure verified for candidate <strong>${candidateName}</strong> with <strong>${companyName}</strong>.</p>
    <p style="font-size: 13.5px; color: #334155;">Calculated Agency Revenue: <strong style="color: #047857; font-size: 16px;">${revenueStr}</strong></p>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Placement Closed for ${candidateName} at ${companyName}. Revenue: ${revenueStr}`
  };
}

export function generateApplicationReceivedTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  jobTitle: string;
  companyName: string;
}): RenderedEmail {
  const { agency, candidateName, jobTitle, companyName } = params;
  const title = `Application Received: ${jobTitle} at ${companyName}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Dear <strong>${candidateName}</strong>,</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.6;">Thank you for applying for the position of <strong>${jobTitle}</strong> at <strong>${companyName}</strong> through our recruitment portal.</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.6;">Our talent acquisition team and automated resume screening pipeline are currently reviewing your candidate profile and experience. We will get in touch with you if your qualifications match our requirement criteria.</p>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Application Received for ${jobTitle} at ${companyName}. We are reviewing your profile.`
  };
}

export function generateApplicationShortlistedTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  jobTitle: string;
  companyName: string;
}): RenderedEmail {
  const { agency, candidateName, jobTitle, companyName } = params;
  const title = `Great News! Your Application for ${jobTitle} has been Shortlisted`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Dear <strong>${candidateName}</strong>,</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.6;">We are pleased to inform you that your profile has been <strong>shortlisted</strong> for the <strong>${jobTitle}</strong> position at <strong>${companyName}</strong>.</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.6;">Our recruitment team will contact you shortly to coordinate your interview schedule and next steps.</p>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Your application for ${jobTitle} at ${companyName} has been shortlisted!`
  };
}

export function generateApplicationRejectedTemplate(params: {
  agency: BaseAgencyContext;
  candidateName: string;
  jobTitle: string;
  companyName: string;
}): RenderedEmail {
  const { agency, candidateName, jobTitle, companyName } = params;
  const title = `Update on your application for ${jobTitle} at ${companyName}`;

  const htmlContent = `
    <p style="margin-top: 0; font-size: 14px; color: #1e293b;">Dear <strong>${candidateName}</strong>,</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.6;">Thank you for your interest in the <strong>${jobTitle}</strong> position at <strong>${companyName}</strong>.</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.6;">After careful review of all candidate applications, we have decided to proceed with other candidates whose profiles align more closely with the immediate requirements of this role.</p>
    <p style="font-size: 13.5px; color: #334155; line-height: 1.6;">We will keep your profile in our active candidate repository for suitable future opportunities.</p>
  `;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent),
    text: `Update regarding your application for ${jobTitle} at ${companyName}.`
  };
}



