/**
 * RecruitOS Dynamic Email Template Engine (PHASE EM-01)
 * Generates dynamic, production-grade HTML and Plain Text emails for all platform events.
 * Fully multi-tenant aware with dynamic Agency branding and master layout system.
 */

export interface RenderedEmail {
  subject: string;
  html: string;
  text: string;
}

export interface BaseAgencyContext {
  agencyName?: string | null;
  logoUrl?: string | null;
  senderName?: string | null;
  replyToEmail?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  websiteUrl?: string | null;
}

const DEFAULT_BASE_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

/**
 * Master Email Layout Wrapper
 * Enforces responsive 700px max-width container, header branding, and RecruitOS footer.
 */
function wrapMasterLayout(
  agency: BaseAgencyContext,
  title: string,
  contentHtml: string,
  cta?: { label: string; url: string } | null
): string {
  const displayAgencyName = agency.agencyName || agency.senderName || 'RecruitOS Agency';
  const logoHtml = agency.logoUrl
    ? `<img src="${agency.logoUrl}" alt="${displayAgencyName}" style="max-height: 44px; width: auto; display: block; margin-bottom: 8px;" />`
    : '';

  const ctaButtonHtml = cta
    ? `
      <div style="margin: 32px 0 24px 0; text-align: center;">
        <a href="${cta.url}" target="_blank" style="background-color: #0d3859; color: #ffffff; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 800; padding: 14px 28px; text-decoration: none; border-radius: 8px; display: inline-block; box-shadow: 0 4px 6px -1px rgba(13, 56, 89, 0.2);">
          ${cta.label}
        </a>
      </div>
    `
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; }
    table { border-collapse: collapse; }
    @media only screen and (max-width: 640px) {
      .container { width: 100% !important; padding: 12px !important; }
      .content-box { padding: 20px 16px !important; }
      .table-responsive { display: block !important; width: 100% !important; overflow-x: auto !important; }
    }
  </style>
</head>
<body style="margin: 0; padding: 24px 0; background-color: #f8fafc;">
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td align="center">
        <!-- 700px Container -->
        <table role="presentation" class="container" width="700" border="0" cellspacing="0" cellpadding="0" style="width: 700px; max-width: 700px; margin: 0 auto;">
          
          <!-- Header Branding -->
          <tr>
            <td style="padding: 16px 24px; background-color: #ffffff; border-top-left-radius: 12px; border-top-right-radius: 12px; border-bottom: 2px solid #e2e8f0;">
              <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    ${logoHtml}
                    <div style="font-size: 20px; font-weight: 800; color: #0d3859; letter-spacing: -0.5px; text-transform: uppercase;">
                      ${displayAgencyName}
                    </div>
                  </td>
                  <td align="right" style="font-size: 11px; color: #64748b; font-weight: 600;">
                    Official Notification
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Main Body -->
          <tr>
            <td class="content-box" style="padding: 32px; background-color: #ffffff; border-bottom-left-radius: 12px; border-bottom-right-radius: 12px; box-shadow: 0 4px 12px rgba(15, 23, 42, 0.05);">
              
              <h2 style="margin: 0 0 20px 0; font-size: 20px; font-weight: 800; color: #0f172a; letter-spacing: -0.3px;">
                ${title}
              </h2>

              <div style="font-size: 14px; line-height: 1.6; color: #334155;">
                ${contentHtml}
              </div>

              ${ctaButtonHtml}

            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 24px 16px; text-align: center; font-size: 12px; color: #94a3b8; line-height: 1.5;">
              <p style="margin: 0 0 4px 0; font-weight: 600; color: #64748b;">
                ${displayAgencyName} ${agency.contactEmail ? `• ${agency.contactEmail}` : ''}
              </p>
              <p style="margin: 0;">
                This email was generated by <strong style="color: #0d3859;">RecruitOS</strong> Talent Platform
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

// =========================================================
// 1. REQUIREMENT RECEIVED TEMPLATE (Recipient: Agency Owner)
// =========================================================
export interface RequirementReceivedParams {
  agency: BaseAgencyContext;
  requirementId: string;
  positionTitle: string;
  companyName: string;
  contactPerson?: string;
  source?: string;
  receivedDate?: string;
  baseUrl?: string;
}

export function generateRequirementReceivedTemplate(params: RequirementReceivedParams): RenderedEmail {
  const { agency, requirementId, positionTitle, companyName, contactPerson, source, receivedDate, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `New Requirement Received - ${positionTitle}`;
  const ctaUrl = `${appUrl}/incoming-requirements/${requirementId}`;

  const htmlContent = `
    <p style="margin-top: 0;">A new client hiring requirement has been received and logged in your inbox pipeline.</p>

    <div style="background-color: #f1f5f9; border-left: 4px solid #0d3859; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #475569;">Requirement ID:</td><td>REQ-${requirementId.slice(0, 8).toUpperCase()}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Position Title:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Company Name:</td><td>${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Contact Person:</td><td>${contactPerson || 'N/A'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Source:</td><td>${source || 'Website Widget'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Received Date:</td><td>${receivedDate || new Date().toLocaleDateString('en-US')}</td></tr>
      </table>
    </div>

    <p>Please review the requirement details and assign a lead recruiter to start sourcing.</p>
  `;

  const textContent = `New Requirement Received - ${positionTitle}\n
Requirement ID: REQ-${requirementId.slice(0, 8).toUpperCase()}
Position: ${positionTitle}
Company: ${companyName}
Contact Person: ${contactPerson || 'N/A'}
Source: ${source || 'Website Widget'}
Received Date: ${receivedDate || new Date().toLocaleDateString('en-US')}

View Requirement: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'View Requirement', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 2. REQUIREMENT ASSIGNED TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface RequirementAssignedParams {
  agency: BaseAgencyContext;
  requirementId: string;
  positionTitle: string;
  companyName: string;
  priority?: string;
  assignedBy?: string;
  assignedDate?: string;
  baseUrl?: string;
}

export function generateRequirementAssignedTemplate(params: RequirementAssignedParams): RenderedEmail {
  const { agency, requirementId, positionTitle, companyName, priority, assignedBy, assignedDate, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `New Requirement Assigned - ${positionTitle}`;
  const ctaUrl = `${appUrl}/incoming-requirements/${requirementId}`;

  const htmlContent = `
    <p style="margin-top: 0;">You have been assigned as lead recruiter for a new hiring requirement.</p>

    <div style="background-color: #f1f5f9; border-left: 4px solid #0d3859; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #475569;">Position Title:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Company Name:</td><td>${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Priority:</td><td><span style="background-color: #e0f2fe; color: #0369a1; padding: 2px 8px; border-radius: 4px; font-weight: 700; font-size: 11px;">${(priority || 'HIGH').toUpperCase()}</span></td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Assigned By:</td><td>${assignedBy || 'Agency Administrator'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Assigned Date:</td><td>${assignedDate || new Date().toLocaleDateString('en-US')}</td></tr>
      </table>
    </div>

    <p>Click below to open the requirement workspace, review candidate specifications, and convert it to an active Job Mandate.</p>
  `;

  const textContent = `New Requirement Assigned - ${positionTitle}\n
Position: ${positionTitle}
Company: ${companyName}
Priority: ${priority || 'HIGH'}
Assigned By: ${assignedBy || 'Agency Administrator'}
Assigned Date: ${assignedDate || new Date().toLocaleDateString('en-US')}

Open Requirement: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Open Requirement', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 3. REQUIREMENT ACCEPTED TEMPLATE (Recipient: Client)
// =========================================================
export interface RequirementAcceptedParams {
  agency: BaseAgencyContext;
  clientName: string;
  positionTitle: string;
  companyName: string;
  recruiterName?: string;
  recruiterEmail?: string;
  recruiterPhone?: string;
  mandateId?: string;
  baseUrl?: string;
}

export function generateRequirementAcceptedTemplate(params: RequirementAcceptedParams): RenderedEmail {
  const { agency, clientName, positionTitle, companyName, recruiterName, recruiterEmail, recruiterPhone, mandateId, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Requirement Accepted - ${positionTitle}`;
  const ctaUrl = `${appUrl}/incoming-requirements/${mandateId || ''}`;

  const htmlContent = `
    <p style="margin-top: 0;">Dear <strong>${clientName}</strong>,</p>
    <p>Thank you for sharing your hiring requirement with us. Our recruitment team has reviewed and accepted the requirement.</p>

    <div style="background-color: #f1f5f9; border-left: 4px solid #10b981; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #475569;">Position Title:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Company Name:</td><td>${companyName}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Assigned Recruiter:</td><td style="font-weight: 700;">${recruiterName || 'Talent Sourcing Specialist'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Recruiter Email:</td><td>${recruiterEmail || agency.replyToEmail || 'contact@agency.com'}</td></tr>
        <tr><td style="font-weight: 700; color: #475569;">Recruiter Phone:</td><td>${recruiterPhone || agency.contactPhone || 'N/A'}</td></tr>
      </table>
    </div>

    <p>Our team has initiated candidate matching and headhunting for this mandate. We will share shortlisted candidate profiles shortly.</p>
  `;

  const textContent = `Dear ${clientName},\n
Thank you for sharing your hiring requirement. Our recruitment team has reviewed and accepted the requirement.\n
Position: ${positionTitle}
Company: ${companyName}
Assigned Recruiter: ${recruiterName || 'Talent Sourcing Specialist'}
Recruiter Email: ${recruiterEmail || agency.replyToEmail || 'contact@agency.com'}
Recruiter Phone: ${recruiterPhone || 'N/A'}

View Requirement Status: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'View Requirement Status', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 4. REQUIREMENT REJECTED TEMPLATE (Recipient: Client)
// =========================================================
export interface RequirementRejectedParams {
  agency: BaseAgencyContext;
  clientName: string;
  positionTitle: string;
  companyName: string;
  reason?: string;
}

export function generateRequirementRejectedTemplate(params: RequirementRejectedParams): RenderedEmail {
  const { agency, clientName, positionTitle, companyName, reason } = params;
  const title = `Requirement Update - ${positionTitle}`;

  const htmlContent = `
    <p style="margin-top: 0;">Dear <strong>${clientName}</strong>,</p>
    <p>Thank you for submitting your hiring requirement for <strong>${positionTitle}</strong> (${companyName}).</p>
    <p>After reviewing our current capacity and domain focus, we regret to inform you that we are unable to accept this specific requirement at this time.</p>

    ${
      reason
        ? `<div style="background-color: #fff1f2; border-left: 4px solid #e11d48; padding: 16px; border-radius: 6px; margin: 20px 0; font-size: 13px; color: #9f1239;">
            <strong>Reason for Non-Acceptance:</strong><br />${reason}
          </div>`
        : ''
    }

    <p>We appreciate your interest in partnering with us and look forward to collaborating on future hiring needs.</p>
  `;

  const textContent = `Dear ${clientName},\n
Thank you for submitting your hiring requirement for ${positionTitle} (${companyName}).
Regrettably, we are unable to accept this requirement at this time.

${reason ? `Reason: ${reason}\n` : ''}
We appreciate your interest in working with us.`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, null),
    text: textContent
  };
}

// =========================================================
// 5. CANDIDATE SUBMISSION TRACKER TEMPLATE (Recipient: Client)
// =========================================================
export interface CandidateTrackerRow {
  date?: string;
  source?: string;
  clientName?: string;
  appliedPositionName?: string;
  candidateName: string;
  emailId: string;
  number: string;
  location: string;
  readyToRelocate: string;
  experience: string;
  relevantExperience: string;
  designation: string;
  qualification: string;
  currentLastCompany: string;
  currentSalary: string;
  expectedSalary: string;
  noticePeriod: string;
  reasonOfLeaving: string;
  offerInHand: string;
  resumeUrl?: string | null;
}

export interface CandidateSubmissionTemplateParams {
  agency: BaseAgencyContext;
  clientName: string;
  positionTitle: string;
  recruiterCoverNote?: string;
  token: string;
  candidates: CandidateTrackerRow[];
  baseUrl?: string;
}

export function generateCandidateSubmissionTemplate(params: CandidateSubmissionTemplateParams): RenderedEmail {
  const { agency, clientName, positionTitle, recruiterCoverNote, token, candidates, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Candidate Submission Tracker - ${positionTitle}`;
  const reviewPortalUrl = `${appUrl}/client-review/${token}`;

  const rowsHtml = candidates.map(c => `
    <tr style="border-bottom: 1px solid #cbd5e1;">
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px; font-weight: 500;">${c.date || new Date().toLocaleDateString()}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.source || 'Headhunted'}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.clientName || clientName}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px; font-weight: 600;">${c.appliedPositionName || positionTitle}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px; font-weight: 700; color: #0d3859;">${c.candidateName}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.emailId}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.number}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.location}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.readyToRelocate}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.experience}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.relevantExperience}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.designation}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.qualification}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.currentLastCompany}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.currentSalary}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.expectedSalary}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.noticePeriod}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.reasonOfLeaving}</td>
      <td style="padding: 8px; border-right: 1px solid #cbd5e1; font-size: 11px;">${c.offerInHand}</td>
      <td style="padding: 8px; text-align: center; font-size: 11px;">
        ${c.resumeUrl 
          ? `<a href="${c.resumeUrl}" target="_blank" style="color: #0284c7; font-weight: 700; text-decoration: underline;">View Resume</a>`
          : '<span style="color: #94a3b8;">N/A</span>'}
      </td>
    </tr>
  `).join('');

  const htmlContent = `
    <p style="margin-top: 0;">Dear <strong>${clientName}</strong>,</p>
    <p>Please find below the candidate shortlist for <strong>${positionTitle}</strong> submitted for your review.</p>

    ${
      recruiterCoverNote
        ? `<div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #0d3859; padding: 14px; border-radius: 6px; margin: 16px 0; font-size: 13px; color: #334155;">
            <strong style="color: #0d3859;">Recruiter Note:</strong><br />${recruiterCoverNote}
          </div>`
        : ''
    }

    <div style="margin: 24px 0; text-align: center;">
      <a href="${reviewPortalUrl}" target="_blank" style="background-color: #0d3859; color: #ffffff; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 800; padding: 14px 28px; text-decoration: none; border-radius: 8px; display: inline-block;">
        Review Submitted Candidates
      </a>
    </div>

    <!-- 19-Column Candidate Tracker Table -->
    <div style="margin-top: 24px; overflow-x: auto; -webkit-overflow-scrolling: touch;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="min-width: 1200px; border: 1px solid #cbd5e1; border-collapse: collapse; font-size: 11px; text-align: left;">
        <thead>
          <tr style="background-color: #0d3859; color: #ffffff; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px;">
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Date</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Source</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Client Name</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Applied Position Name</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Candidate Name</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Email ID</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Number</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Location</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Ready To Relocate</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Experience</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Relevant Experience</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Designation</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Qualification</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Current/Last Company</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Current Salary</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Expected Salary</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Notice Period</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Reason Of Leaving</th>
            <th style="padding: 10px 8px; border-right: 1px solid #1e293b;">Offer In Hand</th>
            <th style="padding: 10px 8px; text-align: center;">Resume</th>
          </tr>
        </thead>
        <tbody style="background-color: #ffffff; color: #1e293b;">
          ${rowsHtml}
        </tbody>
      </table>
    </div>

    <p style="margin-top: 24px;">Please click the button above to record your interview decisions (Shortlist / Hold / Reject) for each candidate.</p>
  `;

  const textContent = `Dear ${clientName},\n
Candidate Submission Tracker - ${positionTitle}\n
Total Candidates: ${candidates.length}
${recruiterCoverNote ? `Recruiter Note: ${recruiterCoverNote}\n` : ''}
Access Review Portal: ${reviewPortalUrl}\n
Candidates:\n${candidates.map(c => `- ${c.candidateName} | ${c.designation} | Exp: ${c.experience} | Current CTC: ${c.currentSalary} | Notice: ${c.noticePeriod}`).join('\n')}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Review Submitted Candidates', url: reviewPortalUrl }),
    text: textContent
  };
}

// =========================================================
// 6. CLIENT INTERVIEW TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface ClientInterviewParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  clientName: string;
  submissionId?: string;
  baseUrl?: string;
}

export function generateInterviewSelectedTemplate(params: ClientInterviewParams): RenderedEmail {
  const { agency, candidateName, positionTitle, clientName, submissionId, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Client Selected Candidate For Interview`;
  const ctaUrl = `${appUrl}/submissions`;

  const htmlContent = `
    <p style="margin-top: 0;">Great news! The client has selected a candidate for an interview.</p>

    <div style="background-color: #ecfdf5; border-left: 4px solid #10b981; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #047857;">Candidate Name:</td><td style="font-weight: 800; color: #065f46;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Position:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #047857;">Client Name:</td><td>${clientName}</td></tr>
      </table>
    </div>

    <p>Please log into RecruitOS to schedule interview slots with the candidate and client team.</p>
  `;

  const textContent = `Client Selected Candidate For Interview\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Client Name: ${clientName}

Open Candidate Submission: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Open Candidate Submission', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 7. CLIENT HOLD TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface ClientHoldParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  clientName: string;
  notes?: string;
  baseUrl?: string;
}

export function generateCandidateHoldTemplate(params: ClientHoldParams): RenderedEmail {
  const { agency, candidateName, positionTitle, clientName, notes, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Candidate Put On Hold By Client`;
  const ctaUrl = `${appUrl}/submissions`;

  const htmlContent = `
    <p style="margin-top: 0;">The client has put a submitted candidate on hold.</p>

    <div style="background-color: #fffbeb; border-left: 4px solid #f59e0b; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #b45309;">Candidate Name:</td><td style="font-weight: 800; color: #78350f;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #b45309;">Position:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #b45309;">Client Name:</td><td>${clientName}</td></tr>
        ${notes ? `<tr><td style="font-weight: 700; color: #b45309;">Client Notes:</td><td>${notes}</td></tr>` : ''}
      </table>
    </div>

    <p>The candidate status has been updated to ON_HOLD in the recruitment pipeline.</p>
  `;

  const textContent = `Candidate Put On Hold By Client\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Client Name: ${clientName}
${notes ? `Notes: ${notes}\n` : ''}
Open Submissions: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Open Submissions', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 8. CLIENT REJECT TEMPLATE (Recipient: Recruiter)
// =========================================================
export interface ClientRejectParams {
  agency: BaseAgencyContext;
  candidateName: string;
  positionTitle: string;
  clientName: string;
  notes?: string;
  baseUrl?: string;
}

export function generateCandidateRejectedTemplate(params: ClientRejectParams): RenderedEmail {
  const { agency, candidateName, positionTitle, clientName, notes, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Candidate Rejected By Client`;
  const ctaUrl = `${appUrl}/submissions`;

  const htmlContent = `
    <p style="margin-top: 0;">The client has declined a submitted candidate profile.</p>

    <div style="background-color: #fff1f2; border-left: 4px solid #e11d48; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #be123c;">Candidate Name:</td><td style="font-weight: 800; color: #881337;">${candidateName}</td></tr>
        <tr><td style="font-weight: 700; color: #be123c;">Position:</td><td style="font-weight: 700; color: #0d3859;">${positionTitle}</td></tr>
        <tr><td style="font-weight: 700; color: #be123c;">Client Name:</td><td>${clientName}</td></tr>
        ${notes ? `<tr><td style="font-weight: 700; color: #be123c;">Rejection Feedback:</td><td>${notes}</td></tr>` : ''}
      </table>
    </div>

    <p>Please review candidate pipeline feedback and continue sourcing alternative matches.</p>
  `;

  const textContent = `Candidate Rejected By Client\n
Candidate Name: ${candidateName}
Position: ${positionTitle}
Client Name: ${clientName}
${notes ? `Feedback: ${notes}\n` : ''}
Open Submissions: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Open Submissions', url: ctaUrl }),
    text: textContent
  };
}

// =========================================================
// 9. SUBSCRIPTION EXPIRY TEMPLATE (Recipient: Agency Owners / Super Admin)
// =========================================================
export interface SubscriptionExpiryParams {
  agency: BaseAgencyContext;
  agencyName: string;
  planName?: string;
  expiryDate?: string;
  daysRemaining: number;
  baseUrl?: string;
}

export function generateSubscriptionExpiryTemplate(params: SubscriptionExpiryParams): RenderedEmail {
  const { agency, agencyName, planName, expiryDate, daysRemaining, baseUrl } = params;
  const appUrl = baseUrl || DEFAULT_BASE_URL;
  const title = `Subscription Expiring Soon - ${agencyName}`;
  const ctaUrl = `${appUrl}/settings`;

  const htmlContent = `
    <p style="margin-top: 0;">This is an automated alert that your agency subscription plan is approaching its expiration date.</p>

    <div style="background-color: #fffbeb; border-left: 4px solid #d97706; padding: 16px; border-radius: 6px; margin: 20px 0;">
      <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="4" style="font-size: 13px; color: #1e293b;">
        <tr><td width="35%" style="font-weight: 700; color: #92400e;">Agency Name:</td><td style="font-weight: 800; color: #0d3859;">${agencyName}</td></tr>
        <tr><td style="font-weight: 700; color: #92400e;">Subscription Plan:</td><td>${planName || 'Enterprise Tier'}</td></tr>
        <tr><td style="font-weight: 700; color: #92400e;">Expiration Date:</td><td>${expiryDate || 'Within 7 Days'}</td></tr>
        <tr><td style="font-weight: 700; color: #92400e;">Days Remaining:</td><td><strong style="color: #dc2626; font-size: 15px;">${daysRemaining} Day(s)</strong></td></tr>
      </table>
    </div>

    <p>Please renew your subscription to maintain uninterrupted platform access, active client portals, and job board widgets.</p>
  `;

  const textContent = `Subscription Expiring Soon - ${agencyName}\n
Agency Name: ${agencyName}
Subscription Plan: ${planName || 'Enterprise Tier'}
Expiration Date: ${expiryDate || 'Within 7 Days'}
Days Remaining: ${daysRemaining} Day(s)

Manage Subscription: ${ctaUrl}`;

  return {
    subject: title,
    html: wrapMasterLayout(agency, title, htmlContent, { label: 'Manage Subscription', url: ctaUrl }),
    text: textContent
  };
}
